import assert from "node:assert/strict";
import { tasteProfileSchema, type VideoResult, type YoutubeBrowseRequest } from "@music-os/core";
import { effectiveTasteProfile } from "../services/taste-learning-service.js";
import { youtubeHome, youtubePreferences } from "../services/youtube-personalization.js";
import { youtubeMatchingChannels } from "../services/youtube-browse.js";

const profile = tasteProfileSchema.parse({ favoriteArtists: [" Björk ", "Portishead", "björk", "Blocked"], preferredGenres: ["Trip hop", "Ambient", "ambient", "Pop"], blockedArtists: ["blocked"], blockedGenres: ["pop"] });
const preferences = youtubePreferences(profile);
assert.deepEqual(preferences.topics.map(topic => topic.label), ["Trip hop", "Ambient"]);
assert.deepEqual(preferences.homeQueries, ["Björk music", "Portishead music", "Trip hop music", "Ambient music"]);
assert.equal(preferences.personalized, true);
assert.equal(youtubePreferences(tasteProfileSchema.parse({})).personalized, false);
const video = (id: string, channel = "Björk"): VideoResult => ({ id, channel, title: id, url: `https://www.youtube.com/watch?v=${id}`, duration: 123, thumbnail: null, channelId: "UC" + "a".repeat(22), channelUrl: "https://www.youtube.com/channel/UC" + "a".repeat(22) + "/videos" });
const calls: YoutubeBrowseRequest[] = [];
const browse = async (request: YoutubeBrowseRequest) => {
  calls.push(request);
  return { results: [video("sharedvideo"), video(request.q.padEnd(11, "x").slice(0,11)), video("blocked_vid", "Blocked - Topic")], title: request.q, nextPage: 2, sourceUrl: "https://www.youtube.com" };
};
const home = await youtubeHome(profile, browse);
assert.equal(calls.length, 3);
assert.deepEqual(calls.map(request => request.q), preferences.homeQueries.slice(0,3));
assert.equal(home.results.filter(result => result.id === "sharedvideo").length, 1);
assert.equal(home.results.some(result => result.id === "blocked_vid"), false);
assert.equal(home.nextPage, 2);
await youtubeHome(profile, browse, 2);
assert.equal(calls.at(-1)?.q, "Ambient music");
await youtubeHome(profile, browse, 3);
assert.equal(calls.at(-1)?.page, 2);
const before = calls.length;
assert.equal((await youtubeHome(tasteProfileSchema.parse({}), browse)).results.length, 0);
assert.equal(calls.length, before);
await assert.rejects(youtubeHome(profile, browse, 0));
const channels = youtubeMatchingChannels("Björk", [video("abcdefghijk", "Björk Official"), video("lmnopqrstuv", "Björk - Topic"), video("randomvideo", "Björk fan archives")]);
assert.equal(channels.length, 1);
assert.equal(channels[0].matchedVideos, 2);
assert.equal(youtubeMatchingChannels("Björk live", [video("abcdefghijk")]).length, 0);
assert.equal(youtubeMatchingChannels("Björk", [{ ...video("abcdefghijk"), channelId: undefined }]).length, 0);
const partial = await youtubeHome(profile, async request => request.q.startsWith("Björk") ? Promise.reject(new Error("offline")) : browse(request));
assert.ok(partial.results.length > 0);
await assert.rejects(youtubeHome(profile, async () => { throw new Error("offline"); }), /offline/);
// Match Settings: an empty manual field inherits learned tastes; manual blocks still win.
const manual = tasteProfileSchema.parse({ favoriteAlbums: ["Album Artist — Favorite Album"], blockedArtists: ["Blocked"], blockedGenres: ["Pop"] });
const learned = tasteProfileSchema.parse({ favoriteArtists: ["Learned Artist", "Blocked"], preferredGenres: ["Indie Rock", "Pop"] });
const effective = effectiveTasteProfile(manual, learned);
const learnedPreferences = youtubePreferences(effective);
assert.equal(learnedPreferences.personalized, true);
assert.deepEqual(learnedPreferences.topics.map(topic => topic.label), ["Indie Rock"]);
assert.deepEqual(learnedPreferences.homeQueries, ["Learned Artist music", "Indie Rock music"]);
const learnedCalls: string[] = [];
await youtubeHome(effective, async request => { learnedCalls.push(request.q); return browse(request); });
assert.deepEqual(learnedCalls, learnedPreferences.homeQueries);
assert.deepEqual(youtubePreferences(manual).homeQueries, ["Album Artist music"], "Album preferences also seed home when no artist list exists");
assert.deepEqual(youtubePreferences(effectiveTasteProfile(tasteProfileSchema.parse({ favoriteArtists: ["Explicit Artist"] }), learned)).homeQueries.slice(0,1), ["Explicit Artist music"], "Explicit Settings values retain precedence");
const formatProfile = tasteProfileSchema.parse({ preferredGenres: ["FLAC 16-44.1", "FLAC", "MP3 320kbps", "Indie Rock", "J-Pop", "Lo-Fi", "8-bit", "Glitch", "Chiptune"] });
const formatPreferences = youtubePreferences(formatProfile);
assert.deepEqual(formatPreferences.topics.map(topic => topic.label), ["Indie Rock", "J-Pop", "Lo-Fi", "8-bit", "Glitch", "Chiptune"]);
assert.equal(formatPreferences.homeQueries.some(query => /FLAC|MP3/.test(query)), false);
assert.equal(formatProfile.preferredGenres[0], "FLAC 16-44.1", "Filtering must not alter stored taste data");
console.log("youtube personalization smoke passed");
