import assert from "node:assert/strict";
import { mkdtemp, readFile, rm, stat } from "node:fs/promises";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { createServer } from "node:http";
import { YoutubePlaybackService, validateYoutubeCookies, youtubeMediaUrl } from "../services/youtube-playback-service.js";
const directory = await mkdtemp(join(tmpdir(), "youtube-playback-smoke-"));
const cookies = "# Netscape HTTP Cookie File\n.youtube.com\tTRUE\t/\tTRUE\t2000000000\tSID\tfixture-only\n";
let args: string[] = [];
let audioOnly = false;
let redirect = false;
let receivedRange: string | null = null;
let calls = 0;
const service = new YoutubePlaybackService(directory, async (value) => { args = value; return JSON.stringify({ id: "abcdefghijk", title: "Fixture", channel: "Channel", duration: 120, acodec: "mp4a", vcodec: audioOnly ? "none" : "avc1", url: "https://rr1.googlevideo.com/videoplayback?expire=9999999999", http_headers: { "User-Agent": "fixture", Cookie: "must-not-forward" } }); }, (async (_url: unknown, options: RequestInit) => {
  calls++;
  const headers = new Headers(options.headers);
  assert.equal(headers.get("cookie"), null);
  receivedRange = headers.get("range");
  if (redirect) return new Response(null, { status: 302, headers: { location: "http://127.0.0.1/secrets" } });
  return new Response(options.method === "HEAD" ? null : "234", { status: 206, headers: { "content-type": "video/mp4", "content-length": "3", "content-range": "bytes 2-4/10", "accept-ranges": "bytes" } });
}) as typeof fetch);
const server = createServer((req, res) => { const url = new URL(req.url!, "http://localhost"); void service.stream(url.searchParams.get("token") ?? "", req, res); });
await new Promise<void>(resolve => server.listen(0, "127.0.0.1", resolve));
const address = server.address() as import("node:net").AddressInfo;
const base = "http://127.0.0.1:" + address.port;
try {
  for (const input of ["https://googlevideo.com.evil.test/x", "http://rr1.googlevideo.com/x", "https://user:pass@rr1.googlevideo.com/x", "https://127.0.0.1/x"]) assert.throws(() => youtubeMediaUrl(input));
  assert.throws(() => validateYoutubeCookies(cookies.replace(".youtube.com", ".example.com")));
  assert.throws(() => validateYoutubeCookies("plain text"));
  assert.throws(() => validateYoutubeCookies(cookies + "x".repeat(1024 * 1024)));
  assert.equal((await service.session()).configured, false);
  await service.saveSession(cookies);
  assert.equal((await stat(join(directory, "session.cookies.txt"))).mode & 0o777, 0o600);
  assert.equal(await readFile(join(directory, "session.cookies.txt"), "utf8"), cookies);
  assert.deepEqual(await service.session(), { configured: true });
  const result = await service.resolve("https://youtu.be/abcdefghijk");
  assert.equal(result.audioOnly, false);
  assert.ok(args[args.indexOf("-f") + 1].startsWith("bestaudio["), "Audio is the default stream preference");
  await service.resolve("https://youtu.be/abcdefghijk", "video");
  assert.ok(args[args.indexOf("-f") + 1].includes("[vcodec!=none]"));
  assert.ok(!args[args.indexOf("-f") + 1].includes("bestaudio"), "Video must never silently fall back to audio");
  assert.equal(result.video.title, "Fixture");
  assert.ok(args.includes("--cookies")); assert.ok(args.includes("--skip-download"));
  await assert.rejects(stat(args[args.indexOf('--cookies') + 1]));
  assert.ok(!JSON.stringify(result).includes("googlevideo"));
  const response = await fetch(base + result.src, { headers: { Range: "bytes=2-4" } });
  assert.equal(response.status, 206); assert.equal(await response.text(), "234"); assert.equal(receivedRange, "bytes=2-4");
  assert.equal(response.headers.get("content-range"), "bytes 2-4/10");
  assert.equal((await fetch(base + result.src, { method: "HEAD" })).status, 206);
  assert.equal((await fetch(base + result.src, { headers: { Range: "bytes=0-1,4-5" } })).status, 416);
  assert.equal((await fetch(base + "/?token=unknown")).status, 410);
  redirect = true; const before = calls;
  assert.equal((await fetch(base + result.src)).status, 502); assert.equal(calls, before + 1);
  redirect = false; audioOnly = true;
  assert.equal((await service.resolve("https://youtu.be/abcdefghijk")).audioOnly, true);
  await assert.rejects(service.resolve("https://youtu.be/abcdefghijk", "video"), /Video is unavailable/);
  await service.removeSession(); assert.deepEqual(await service.session(), { configured: false });
  assert.equal((await fetch(base + result.src)).status, 410);
  await assert.rejects(service.resolve("https://example.com/abcdefghijk"));
  const failed = new YoutubePlaybackService(directory, async () => { throw new Error("SECRET_COOKIE_CONTENT"); });
  await assert.rejects(failed.resolve("https://youtu.be/abcdefghijk"), error => !String(error).includes("SECRET_COOKIE_CONTENT"));
  let release!: () => void;
  let entered!: () => void;
  const started = new Promise<void>(resolve => { entered = resolve; });
  const gate = new Promise<void>(resolve => { release = resolve; });
  const racing = new YoutubePlaybackService(directory, async () => { entered(); await gate; return JSON.stringify({ id: "abcdefghijk", url: "https://rr1.googlevideo.com/videoplayback", acodec: "aac", vcodec: "avc1" }); });
  await racing.saveSession(cookies);
  const resolving = racing.resolve("https://youtu.be/abcdefghijk");
  await started;
  await racing.removeSession();
  release();
  await assert.rejects(resolving, /session changed/);
  assert.deepEqual(await racing.session(), { configured: false });
  racing.close();
  console.log("YouTube playback smoke passed: range/HEAD streaming, redirect allowlist, token invalidation, audio default and strict video modes, private cookie storage and sanitized extraction failures.");
} finally { service.close(); server.closeAllConnections(); await new Promise<void>(resolve => server.close(() => resolve())); await rm(directory, { recursive: true, force: true }); }